-- MedSync CATMS - Database DDL (02_tables.sql)
-- Target: PostgreSQL 16+ (Neon Cloud / Local)
-- 20 Normalized Relational Entities in strict dependency sequence

USE medsync;

--Sithuka Start

-- 1. User accounts
CREATE TABLE "user" (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    contact_details VARCHAR(255),
    email VARCHAR(255) NOT NULL,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

-- 2. Clinic branches (manager_staff_id FK deferred to 03_constraints.sql to prevent circular dependency)
CREATE TABLE branch (
    branch_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_name VARCHAR(150) NOT NULL,
    location VARCHAR(255) NOT NULL,
    contact_details VARCHAR(255),
    manager_staff_id INTEGER UNIQUE
);

-- 3. User login tracking / session audit
CREATE TABLE users_logins (
    users_logins_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES "user"(user_id),
    login_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_name VARCHAR(100) NOT NULL
);

-- 4. Staff members
CREATE TABLE staff (
    staff_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id INTEGER NOT NULL REFERENCES branch(branch_id),
    users_logins_id INTEGER REFERENCES users_logins(users_logins_id),
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    contact_details VARCHAR(255),
    email VARCHAR(255) NOT NULL,
    staff_type VARCHAR(100) NOT NULL,
    role VARCHAR(100) NOT NULL
);

--Sithuka End


-- Nayanajith Start

-- 5. Patient insurance policies
CREATE TABLE insurance_policy (
    policy_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id INTEGER NOT NULL REFERENCES patient(patient_id),
    provider_id INTEGER NOT NULL REFERENCES insurance_provider(provider_id),
    policy_number INTEGER NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(100) NOT NULL
);

-- 6. Treatment categories
CREATE TABLE treatment_category (
    category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(150) NOT NULL,
    description VARCHAR(500)
);

-- 7. Predefined treatment catalogue
CREATE TABLE treatment (
    treatment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id INTEGER NOT NULL REFERENCES treatment_category(category_id),
    service_code VARCHAR(50) NOT NULL UNIQUE,
    treatment_name VARCHAR(150) NOT NULL,
    standard_price NUMERIC(10, 2) NOT NULL
);

-- 8. Doctor extension
CREATE TABLE doctor (
    doctor_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id INTEGER NOT NULL UNIQUE REFERENCES staff(staff_id),
    doctor_name VARCHAR(150) NOT NULL,
    doctor_license_number VARCHAR(100) NOT NULL UNIQUE
);

-- Nayanajith end


-- Tharushi Start

-- 9. Insurance coverage rules per policy and treatment
CREATE TABLE insurance_coverage (
    coverage_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_id INTEGER NOT NULL REFERENCES insurance_policy(policy_id),
    treatment_id INTEGER NOT NULL REFERENCES treatment(treatment_id),
    coverage_percentage NUMERIC(5, 2) NOT NULL,
    maximum_amount NUMERIC(10, 2) NOT NULL
);

-- 10. Consultation notes
CREATE TABLE consultation_note (
    note_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id INTEGER NOT NULL REFERENCES appointment(appointment_id),
    note_content TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 11. Insurance claims
CREATE TABLE insurance_claim (
    claim_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id INTEGER NOT NULL REFERENCES invoice(invoice_id),
    policy_id INTEGER NOT NULL REFERENCES insurance_policy(policy_id),
    claim_date DATE NOT NULL,
    claim_amount NUMERIC(10, 2) NOT NULL,
    approved_amount NUMERIC(10, 2) DEFAULT 0.00,
    status VARCHAR(100) NOT NULL
);

-- 12. Doctor payments
CREATE TABLE doctor_payment (
    doctor_payment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_id INTEGER NOT NULL REFERENCES doctor(doctor_id),
    appointment_id INTEGER NOT NULL REFERENCES appointment(appointment_id),
    invoice_item_id INTEGER REFERENCES invoice_item(invoice_item_id),
    date DATE NOT NULL,
    time TIME NOT NULL,
    doctor_payment NUMERIC(10, 2) NOT NULL
);

-- Tharushi End


-- Shashika Start

-- 13. Doctor specialties (M:N bridge)
CREATE TABLE doctor_specialty (
    doctor_id INTEGER NOT NULL REFERENCES doctor(doctor_id),
    specialty_id INTEGER NOT NULL REFERENCES specialty(specialty_id),
    PRIMARY KEY (doctor_id, specialty_id)
);

-- 14. Appointments (with self-reference for rescheduling history)
CREATE TABLE appointment (
    appointment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id INTEGER NOT NULL REFERENCES patient(patient_id),
    doctor_id INTEGER NOT NULL REFERENCES doctor(doctor_id),
    branch_id INTEGER NOT NULL REFERENCES branch(branch_id),
    appointment_date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    appointment_type VARCHAR(100) NOT NULL,
    created_by VARCHAR(150) NOT NULL,
    original_appointment_id INTEGER REFERENCES appointment(appointment_id),
    treatment_id INTEGER REFERENCES treatment(treatment_id)
);

-- 15. Invoices
CREATE TABLE invoice (
    invoice_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id INTEGER NOT NULL UNIQUE REFERENCES appointment(appointment_id),
    staff_id INTEGER NOT NULL REFERENCES staff(staff_id),
    invoice_date DATE NOT NULL,
    amount_paid NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    balance NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    status VARCHAR(100) NOT NULL
);

-- 16. Invoice items
CREATE TABLE invoice_item (
    invoice_item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id INTEGER NOT NULL REFERENCES invoice(invoice_id),
    treatment_id INTEGER NOT NULL REFERENCES treatment(treatment_id),
    quantity INTEGER NOT NULL DEFAULT 1,
    unitprice NUMERIC(10, 2) NOT NULL,
    description VARCHAR(255)
);

-- 17. Doctor payments
CREATE TABLE doctor_payment (
    doctor_payment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_id INTEGER NOT NULL REFERENCES doctor(doctor_id),
    appointment_id INTEGER NOT NULL REFERENCES appointment(appointment_id),
    invoice_item_id INTEGER REFERENCES invoice_item(invoice_item_id),
    date DATE NOT NULL,
    time TIME NOT NULL,
    doctor_payment NUMERIC(10, 2) NOT NULL
);

--Shashika End


--Adithya Start

-- 18. Medical specialties catalogue
CREATE TABLE specialty (
    specialty_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    specialty_name VARCHAR(150) NOT NULL,
    description VARCHAR(500)
);

-- 19. Patients
CREATE TABLE patient (
    patient_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id INTEGER NOT NULL REFERENCES branch(branch_id),
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    date_of_birth DATE NOT NULL,
    gender VARCHAR(50) NOT NULL,
    patient_type VARCHAR(100),
    contact_details VARCHAR(255),
    email VARCHAR(255),
    address VARCHAR(500)
);

-- 20. Patient emergency contacts
CREATE TABLE emergency_contact (
    emergency_contact_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id INTEGER NOT NULL REFERENCES patient(patient_id),
    contact_name VARCHAR(150) NOT NULL,
    relationship VARCHAR(100) NOT NULL,
    phone VARCHAR(50) NOT NULL
);

-- 21. Insurance providers
CREATE TABLE insurance_provider (
    provider_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_name VARCHAR(200) NOT NULL UNIQUE,
    contact_details VARCHAR(255)
);

--Adithya end


-- Helpful indexes for foreign-key lookups
CREATE INDEX idx_users_logins_user_id ON users_logins(user_id);
CREATE INDEX idx_staff_branch_id ON staff(branch_id);
CREATE INDEX idx_staff_users_logins_id ON staff(users_logins_id);
CREATE INDEX idx_patient_branch_id ON patient(branch_id);
CREATE INDEX idx_emergency_contact_patient_id ON emergency_contact(patient_id);
CREATE INDEX idx_policy_patient_id ON insurance_policy(patient_id);
CREATE INDEX idx_policy_provider_id ON insurance_policy(provider_id);
CREATE INDEX idx_treatment_category_id ON treatment(category_id);
CREATE INDEX idx_doctor_staff_id ON doctor(staff_id);
CREATE INDEX idx_appointment_patient_id ON appointment(patient_id);
CREATE INDEX idx_appointment_doctor_id ON appointment(doctor_id);
CREATE INDEX idx_appointment_branch_id ON appointment(branch_id);
CREATE INDEX idx_appointment_treatment_id ON appointment(treatment_id);
CREATE INDEX idx_invoice_appointment_id ON invoice(appointment_id);
CREATE INDEX idx_invoice_staff_id ON invoice(staff_id);
CREATE INDEX idx_invoice_item_invoice_id ON invoice_item(invoice_id);
CREATE INDEX idx_invoice_item_treatment_id ON invoice_item(treatment_id);
CREATE INDEX idx_consultation_note_appointment_id ON consultation_note(appointment_id);
CREATE INDEX idx_insurance_coverage_policy_id ON insurance_coverage(policy_id);
CREATE INDEX idx_insurance_coverage_treatment_id ON insurance_coverage(treatment_id);
CREATE INDEX idx_insurance_claim_invoice_id ON insurance_claim(invoice_id);
CREATE INDEX idx_insurance_claim_policy_id ON insurance_claim(policy_id);
CREATE INDEX idx_doctor_payment_doctor_id ON doctor_payment(doctor_id);
CREATE INDEX idx_doctor_payment_appointment_id ON doctor_payment(appointment_id);
CREATE INDEX idx_doctor_payment_invoice_item_id ON doctor_payment(invoice_item_id);
