USE catms_db;

-- Nayanajith 

CREATE TABLE insurance_policy (
    policy_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id INTEGER,
    provider_id INTEGER,
    policy_number INTEGER,
    start_date DATE,
    end_date DATE,
    status VARCHAR(100),
    CONSTRAINT fk_insurance_policy_patient
        FOREIGN KEY (patient_id) REFERENCES patient(patient_id),
    CONSTRAINT fk_insurance_policy_provider
        FOREIGN KEY (provider_id) REFERENCES insurance_provider(provider_id)
);

CREATE TABLE treatment_category (
    category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(150),
    description VARCHAR(500)
);

CREATE TABLE treatment (
    treatment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id INTEGER,
    service_code VARCHAR(100) UNIQUE,
    treatment_name VARCHAR(200),
    standard_price NUMERIC(12,2),
    CONSTRAINT fk_treatment_category
        FOREIGN KEY (category_id) REFERENCES treatment_category(category_id)
);

CREATE TABLE doctor (
    doctor_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id INTEGER,
    doctor_name VARCHAR(200),
    doctor_license_number VARCHAR(100),
    CONSTRAINT fk_doctor_staff
        FOREIGN KEY (staff_id) REFERENCES staff(staff_id)
);

-- nayanajith end


-- Tharushi

CREATE TABLE insurance_coverage (
    coverage_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_id INTEGER,
    treatment_id INTEGER,
    coverage_percentage NUMERIC(5,2),
    maximum_amount NUMERIC(12,2),
    CONSTRAINT fk_insurance_coverage_policy
        FOREIGN KEY (policy_id) REFERENCES insurance_policy(policy_id),
    CONSTRAINT fk_insurance_coverage_treatment
        FOREIGN KEY (treatment_id) REFERENCES treatment(treatment_id)
);

CREATE TABLE consultation_note (
    note_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id INTEGER,
    note_content VARCHAR(2000),
    created_at TIMESTAMP,
    CONSTRAINT fk_consultation_note_appointment
        FOREIGN KEY (appointment_id) REFERENCES appointment(appointment_id)
);

CREATE TABLE insurance_claim (
    claim_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id INTEGER,
    policy_id INTEGER,
    claim_date DATE,
    claim_amount NUMERIC(12,2),
    approved VARCHAR(100),
    amount NUMERIC(12,2),
    status VARCHAR(100),
    CONSTRAINT fk_insurance_claim_invoice
        FOREIGN KEY (invoice_id) REFERENCES invoice(invoice_id),
    CONSTRAINT fk_insurance_claim_policy
        FOREIGN KEY (policy_id) REFERENCES insurance_policy(policy_id)
);

-- Tharushi end