-- Extensions required to retain appointment states and treatment/payment detail
-- without changing the API's existing table/column contract.
DROP VIEW IF EXISTS v_insurance_vs_out_of_pocket;
DROP VIEW IF EXISTS v_invoice_financial_summary;
DROP VIEW IF EXISTS v_treatment_category_usage;
DROP VIEW IF EXISTS v_outstanding_balances;
DROP VIEW IF EXISTS v_doctor_revenue;
DROP VIEW IF EXISTS v_invoice_totals;
DROP VIEW IF EXISTS v_branch_daily_appointment_summary;

ALTER TABLE appointment
    ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'Scheduled';


DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'ck_appointment_status'
          AND conrelid = 'appointment'::regclass
    ) THEN
        ALTER TABLE appointment
            ADD CONSTRAINT ck_appointment_status
            CHECK (status IN ('Scheduled', 'Completed', 'Cancelled'));
    END IF;
END;
$$;


CREATE TABLE IF NOT EXISTS appointment_treatment (
    appointment_treatment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id INTEGER NOT NULL REFERENCES appointment(appointment_id) ON DELETE CASCADE,
    treatment_id INTEGER NOT NULL REFERENCES treatment(treatment_id) ON DELETE RESTRICT,
    quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),
    unitprice NUMERIC(10, 2) NOT NULL CHECK (unitprice >= 0),
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_appointment_treatment UNIQUE (appointment_id, treatment_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_appointment_primary_treatment
    ON appointment_treatment(appointment_id)
    WHERE is_primary;
CREATE INDEX IF NOT EXISTS idx_appointment_treatment_treatment
    ON appointment_treatment(treatment_id);



CREATE TABLE IF NOT EXISTS patient_payment (
    payment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id INTEGER NOT NULL REFERENCES invoice(invoice_id) ON DELETE CASCADE,
    payment_date DATE NOT NULL DEFAULT CURRENT_DATE,
    amount NUMERIC(10, 2) NOT NULL CHECK (amount <> 0),
    payment_method VARCHAR(50) NOT NULL DEFAULT 'Cash',
    reference_number VARCHAR(100),
    payment_type VARCHAR(20) NOT NULL DEFAULT 'Payment'
        CHECK (payment_type IN ('Payment', 'Refund', 'Adjustment')),
    received_by INTEGER REFERENCES staff(staff_id) ON DELETE SET NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_patient_payment_type_amount CHECK (
        (payment_type = 'Payment' AND amount > 0)
        OR (payment_type = 'Refund' AND amount < 0)
        OR (payment_type = 'Adjustment' AND amount <> 0)
    )
);
CREATE INDEX IF NOT EXISTS idx_patient_payment_invoice_date
    ON patient_payment(invoice_id, payment_date);

-- ============================================================================
-- Report views. Date and branch filters can be applied by the querying client.
-- ============================================================================

CREATE OR REPLACE VIEW v_branch_daily_appointment_summary AS
SELECT b.branch_id,
       b.branch_name,
       a.appointment_date,
       COUNT(*) AS total_appointments,
       COUNT(*) FILTER (WHERE a.status = 'Scheduled') AS scheduled_count,
       COUNT(*) FILTER (WHERE a.status = 'Completed') AS completed_count,
       COUNT(*) FILTER (WHERE a.status = 'Cancelled') AS cancelled_count
FROM appointment a
JOIN branch b ON b.branch_id = a.branch_id
GROUP BY b.branch_id, b.branch_name, a.appointment_date;

CREATE OR REPLACE VIEW v_invoice_totals AS
SELECT i.invoice_id,
       i.appointment_id,
       i.invoice_date,
       COALESCE(SUM(ii.quantity * ii.unitprice), i.amount_paid + i.balance)::NUMERIC(12, 2)
           AS billed_amount,
       i.amount_paid,
       i.balance,
       i.status
FROM invoice i
LEFT JOIN invoice_item ii ON ii.invoice_id = i.invoice_id
GROUP BY i.invoice_id, i.appointment_id, i.invoice_date,
         i.amount_paid, i.balance, i.status;


CREATE OR REPLACE VIEW v_doctor_revenue AS
SELECT d.doctor_id,
       d.doctor_name,
       a.branch_id,
       COUNT(DISTINCT a.appointment_id) AS appointment_count,
       COUNT(DISTINCT i.invoice_id) AS invoice_count,
       COALESCE(SUM(vit.billed_amount), 0)::NUMERIC(12, 2) AS billed_revenue,
       COALESCE(SUM(i.amount_paid), 0)::NUMERIC(12, 2) AS collected_revenue
FROM doctor d
LEFT JOIN appointment a ON a.doctor_id = d.doctor_id
LEFT JOIN invoice i ON i.appointment_id = a.appointment_id
LEFT JOIN v_invoice_totals vit ON vit.invoice_id = i.invoice_id
GROUP BY d.doctor_id, d.doctor_name, a.branch_id;

CREATE OR REPLACE VIEW v_outstanding_balances AS
SELECT i.invoice_id,
       a.patient_id,
       p.first_name || ' ' || p.last_name AS patient_name,
       a.branch_id,
       b.branch_name,
       i.invoice_date,
       vit.billed_amount,
       i.amount_paid,
       i.balance,
       i.status
FROM invoice i
JOIN appointment a ON a.appointment_id = i.appointment_id
JOIN patient p ON p.patient_id = a.patient_id
JOIN branch b ON b.branch_id = a.branch_id
JOIN v_invoice_totals vit ON vit.invoice_id = i.invoice_id
WHERE i.balance > 0;