-- Extensions required to retain appointment states and treatment/payment detail
-- without changing the API's existing table/column contract.
DROP VIEW IF EXISTS v_insurance_vs_out_of_pocket;
DROP VIEW IF EXISTS v_invoice_financial_summary;
DROP VIEW IF EXISTS v_treatment_category_usage;
DROP VIEW IF EXISTS v_outstanding_balances;
DROP VIEW IF EXISTS v_doctor_revenue;
DROP VIEW IF EXISTS v_invoice_totals;
DROP VIEW IF EXISTS v_branch_daily_appointment_summary;

ALTER TABLE appointment
    ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'Scheduled';


DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'ck_appointment_status'
          AND conrelid = 'appointment'::regclass
    ) THEN
        ALTER TABLE appointment
            ADD CONSTRAINT ck_appointment_status
            CHECK (status IN ('Scheduled', 'Completed', 'Cancelled'));
    END IF;
END;
$$;


CREATE TABLE IF NOT EXISTS appointment_treatment (
    appointment_treatment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id INTEGER NOT NULL REFERENCES appointment(appointment_id) ON DELETE CASCADE,
    treatment_id INTEGER NOT NULL REFERENCES treatment(treatment_id) ON DELETE RESTRICT,
    quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),
    unitprice NUMERIC(10, 2) NOT NULL CHECK (unitprice >= 0),
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_appointment_treatment UNIQUE (appointment_id, treatment_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_appointment_primary_treatment
    ON appointment_treatment(appointment_id)
    WHERE is_primary;
CREATE INDEX IF NOT EXISTS idx_appointment_treatment_treatment
    ON appointment_treatment(treatment_id);
